2022-11-22 16:52:49,716 ERROR: Exception on / [GET] [in C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\prana\OneDrive\Desktop\SWENG main project\app\main\routes.py", line 36, in index
    return render_template('index.html', title='Home')
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\prana\OneDrive\Desktop\SWENG main project\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\prana\OneDrive\Desktop\SWENG main project\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'html'
    {% block body -%}
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 26, in block 'body'
    {% block content -%}
  File "C:\Users\prana\OneDrive\Desktop\SWENG main project\app\templates\base.html", line 44, in block 'content'
    {% block app_content %}{% endblock %}
  File "C:\Users\prana\OneDrive\Desktop\SWENG main project\app\templates\index.html", line 26, in block 'app_content'
    <a href="{{ url_for('FOC')}}" class="btn btn-outline-success">View</a>
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'FOC'. Did you mean 'main.FOC' instead?
2022-11-22 16:52:56,500 ERROR: Exception on / [GET] [in C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\prana\OneDrive\Desktop\SWENG main project\app\main\routes.py", line 36, in index
    return render_template('index.html', title='Home')
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\prana\OneDrive\Desktop\SWENG main project\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\prana\OneDrive\Desktop\SWENG main project\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'html'
    {% block body -%}
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 26, in block 'body'
    {% block content -%}
  File "C:\Users\prana\OneDrive\Desktop\SWENG main project\app\templates\base.html", line 44, in block 'content'
    {% block app_content %}{% endblock %}
  File "C:\Users\prana\OneDrive\Desktop\SWENG main project\app\templates\index.html", line 26, in block 'app_content'
    <a href="{{ url_for('FOC')}}" class="btn btn-outline-success">View</a>
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'FOC'. Did you mean 'main.FOC' instead?
2022-11-22 16:53:07,564 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\SWENG main project\app\__init__.py:87]
