2022-11-25 01:44:31,208 ERROR: Exception on /FOC [GET] [in C:\Users\prana\anaconda3\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\prana\anaconda3\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\prana\anaconda3\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\prana\anaconda3\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\prana\anaconda3\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\prana\anaconda3\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\prana\OneDrive\Desktop\Dummy\app\main\routes.py", line 77, in FOC
    return render_template("FOC.html", data=list['universal'].most_commits)
TypeError: 'DefaultMeta' object is not subscriptable
2022-11-25 01:45:13,770 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\Dummy\app\__init__.py:87]
2022-11-25 01:45:16,797 ERROR: Exception on /FOC [GET] [in C:\Users\prana\anaconda3\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\prana\anaconda3\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\prana\anaconda3\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\prana\anaconda3\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\prana\anaconda3\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\prana\anaconda3\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\prana\OneDrive\Desktop\Dummy\app\main\routes.py", line 77, in FOC
    return render_template("FOC.html", data=list['universal'].avg_freq)
TypeError: 'DefaultMeta' object is not subscriptable
2022-11-25 01:46:42,319 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\Dummy\app\__init__.py:87]
2022-11-25 02:16:39,351 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\Dummy\app\__init__.py:87]
2022-11-25 02:17:29,755 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\Dummy\app\__init__.py:87]
2022-11-25 02:18:05,198 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\Dummy\app\__init__.py:87]
2022-11-25 02:19:04,114 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\Dummy\app\__init__.py:87]
2022-11-25 02:20:03,359 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\Dummy\app\__init__.py:87]
2022-11-25 02:22:38,666 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\Dummy\app\__init__.py:87]
2022-11-25 02:29:12,862 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\Dummy\app\__init__.py:87]
2022-11-25 02:30:24,274 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\Dummy\app\__init__.py:87]
2022-11-25 02:32:43,687 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\Dummy\app\__init__.py:87]
2022-11-25 20:39:12,114 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\wpfrontend\app\__init__.py:87]
2022-11-26 02:26:16,738 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\wpfrontend\app\__init__.py:87]
2022-11-27 23:20:56,479 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\wpfrontend\app\__init__.py:87]
2022-11-27 23:23:39,134 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\wpfrontend\app\__init__.py:87]
2022-11-27 23:26:14,024 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\wpfrontend\app\__init__.py:87]
2022-11-27 23:29:15,084 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\wpfrontend\app\__init__.py:87]
2022-11-27 23:30:44,631 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\wpfrontend\app\__init__.py:87]
2022-11-27 23:39:28,142 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\wpfrontend\app\__init__.py:87]
2022-11-27 23:50:35,340 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\wpfrontend\app\__init__.py:87]
2022-11-29 10:48:14,674 INFO: Main Project 3 startup [in D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\app\__init__.py:87]
2022-11-29 10:48:30,313 ERROR: Exception on /get_stats_r [GET] [in D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2636, in add
    state = attributes.instance_state(instance)
AttributeError: 'Commit' object has no attribute '_sa_instance_state'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\app\main\routes.py", line 28, in get_stats_r
    get_stats("Su1tanA1bo", "SWENG-Main-Project", "api-calls", "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")
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\app\query.py", line 225, in get_stats
    run_commit_query(owner, repo, branch, auth)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\app\query.py", line 64, in run_commit_query
    commit_info(commit_list)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\app\query.py", line 156, in commit_info
    db.session.add(commit)
  File "<string>", line 2, in add
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2638, in add
    util.raise_(
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\sqlalchemy\util\compat.py", line 210, in raise_
    raise exception
sqlalchemy.orm.exc.UnmappedInstanceError: Class 'commit.Commit' is not mapped
2022-11-29 10:49:55,517 INFO: Main Project 3 startup [in D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\app\__init__.py:87]
2022-11-30 14:35:30,917 INFO: Main Project 3 startup [in D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\app\__init__.py:87]
2022-11-30 14:36:57,771 ERROR: Exception on /SOC [GET] [in D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\app\main\routes.py", line 121, in SOC
    list_Most_Commits += [user_list[name].most_commits[1]]
TypeError: 'int' object is not subscriptable
