2022-11-22 11:59:22,140 ERROR: Exception on /FOC [GET] [in C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\prana\OneDrive\Desktop\SWENG main project\app\main\routes.py", line 73, in FOC
    return render_template("FOC.html")
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\prana\OneDrive\Desktop\SWENG main project\app\templates\FOC.html", line 1, in top-level template code
    {% extends "base.html" %}
jinja2.exceptions.TemplateRuntimeError: extended multiple times
2022-11-22 12:00:31,406 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\SWENG main project\app\__init__.py:87]
2022-11-22 12:01:34,905 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\SWENG main project\app\__init__.py:87]
2022-11-22 12:03:46,973 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\SWENG main project\app\__init__.py:87]
2022-11-22 12:03:52,902 ERROR: Exception on /FOC [GET] [in C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\prana\OneDrive\Desktop\SWENG main project\app\main\routes.py", line 73, in FOC
    return render_template("FOC.html")
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\prana\OneDrive\Desktop\SWENG main project\app\templates\FOC.html", line 1, in top-level template code
    {% extends "base.html" %}
jinja2.exceptions.TemplateRuntimeError: extended multiple times
2022-11-22 12:04:17,891 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\SWENG main project\app\__init__.py:87]
2022-11-22 12:06:10,611 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\SWENG main project\app\__init__.py:87]
2022-11-22 12:06:53,729 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\SWENG main project\app\__init__.py:87]
2022-11-22 12:07:46,074 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\SWENG main project\app\__init__.py:87]
2022-11-22 12:07:47,910 ERROR: Exception on /FOC [GET] [in C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\prana\OneDrive\Desktop\SWENG main project\app\main\routes.py", line 73, in FOC
    return render_template("FOC.html")
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\prana\OneDrive\Desktop\SWENG main project\app\templates\FOC.html", line 1, in top-level template code
    {% extends "base.html" %}
jinja2.exceptions.TemplateRuntimeError: extended multiple times
2022-11-22 12:13:14,767 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\SWENG main project\app\__init__.py:87]
2022-11-22 12:13:20,555 ERROR: Exception on /FOC [GET] [in C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\prana\OneDrive\Desktop\SWENG main project\app\main\routes.py", line 73, in FOC
    return render_template("FOC.html")
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\prana\OneDrive\Desktop\SWENG main project\app\templates\FOC.html", line 1, in top-level template code
    {% extends 'chartjs/base.html' %}
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\prana\anaconda3\envs\sweng\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: chartjs/base.html
2022-11-22 12:14:12,894 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\SWENG main project\app\__init__.py:87]
2022-11-22 12:15:34,374 INFO: Main Project 3 startup [in C:\Users\prana\OneDrive\Desktop\SWENG main project\app\__init__.py:87]
