2022-11-15 16:48:49,188 INFO: Microblog startup [in D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\app\__init__.py:87]
2022-11-15 16:48:56,436 ERROR: Exception on /auth/login [GET] [in D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\app\auth\routes.py", line 39, in login
    return render_template('auth/login.html', title=_('Sign In'), form=form)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\app\templates\auth\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block 'body'
    {% block navbar %}
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\app\templates\base.html", line 17, in block 'navbar'
    <a class="navbar-brand" href="{{ url_for('index') }}">Main Project 3</a>
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2022-11-15 16:49:00,799 ERROR: Exception on /favicon.ico [GET] [in D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 1785, in dispatch_request
    self.raise_routing_exception(req)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 1767, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\ctx.py", line 351, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\werkzeug\routing\map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 1666, in handle_user_exception
    return self.handle_http_exception(e)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 1606, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\app\errors\handlers.py", line 19, in not_found_error
    return render_template('errors/404.html'), 404
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\app\templates\errors\404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block 'body'
    {% block navbar %}
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\app\templates\base.html", line 17, in block 'navbar'
    <a class="navbar-brand" href="{{ url_for('index') }}">Main Project 3</a>
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\flask\app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "D:\Uni Programs\Software Engineering\Main Project\SWENG-Main-Project\venv\lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
